# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88d4e4328fd49d48a97bc14c9d945fd2b41abd5e6bb6b1202d58d5cccd823b3ee6d2192b45a4197b58b62844c209e9cfb267514e4aa7ce19aa158e2325baf45b

test:
  secret_key_base: 4aff6d0781a4a7f631a70ec35f7c0e12c61021230eaf75a6db3111881a59cd60937a033173f00239368b1334d779573b2e9d2f4945bd1607030e8da07e141e9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
